development:
  adapter: sqlite3
  encoding: utf8
  reconnect: true
  database: db/test.sqlite3
  pool: 5
test:
  adapter: sqlite3
  encoding: utf8
  reconnect: true
  database: db/test.sqlite3
  pool: 5
